FROM --platform=$BUILDPLATFORM golang:1.26 AS build

WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /out/router ./cmd/router

FROM gcr.io/distroless/static:nonroot
COPY --from=build /out/router /router
USER 65532:65532
ENTRYPOINT ["/router"]

