# This rule is not used by the project llm-inference-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to inference.llm.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: llm-inference-operator
    app.kubernetes.io/managed-by: kustomize
  name: llminferencecluster-viewer-role
rules:
- apiGroups:
  - inference.llm.io
  resources:
  - llminferenceclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - inference.llm.io
  resources:
  - llminferenceclusters/status
  verbs:
  - get
